---
# tasks file for nginx
    - name: Install Nginx
      package:
        name: "{{ nginx_package }}"
        state: present
      when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

    - name: Copy Nginx config file CentOS
      template:
        src: /home/ansible/ansible-playground/centos_nginx.conf
        dest: "{{ nginx_conf_centos }}"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart Nginx
      when: ansible_os_family == 'RedHat'

    - name: Copy Nginx sites-enabled file Ubuntu
      template:
        src: /home/ansible/ansible-playground/default
        dest: "{{ nginx_conf_ubuntu }}"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart Nginx
      when: ansible_os_family == 'Debian'
    
    - name: Copy Nginx sites-available file
      template:
        src: /home/ansible/ansible-playground/default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart Nginx
      when: ansible_os_family == 'Debian'