---
# - name: Install and configure mysql database on Ubuntu
#   hosts: dbserver
#   become: true

#   roles:
#     - database

- name: Install and configure python application Ubuntu
  hosts: appserver
  become: true

  roles:
    - git
    - nginx
    # - python
    - application