- name: Install and configure web server
  hosts: webservers
  become: true

  vars:
    web_server:
      - name: Apache
        package: httpd
        service: httpd
        config_template: apache.conf

      - name: Nginx
        package: nginx
        service: nginx
        config_template: nginx.conf

    data_base:
      - name: MySql
        package: mysql-service
      
      - name: MariaDB
        package: mariadb

    php_packages:
      - php
      - php-mysql

  tasks:
    - name: Install PHP packages
      package:
        name: "{{ php_packages }}"
        state: present
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'

    - name: Install web server
      package:
        name: "{{ item.package }}"
        state: present
      with_items: "{{ web_server }}"
      when: ansible_distribution == 'Ubuntu'

    - name: Install web server
      package:
        name: "{{ item.package }}"
        state: present
      with_items: "{{ web_server }}"
      when: ansible_distribution == 'CentOS'

    - name: Install MySQL
      package:
        name: "{{ item.package }}"
        state: present
      with_items: "{{ data_base }}"
      when: ansible_distribution == 'Ubuntu'

    - name: Install MySQL
      package:
        name: "{{ item.package }}"
        state: present
      with_items: "{{ data_base }}"
      when: ansible_distribution == 'CentOS'

    - name: Configure web server
      template:
        src: "{{ item.config_template }}"
        dest: "/etc/{{ item.package }}/{{ item.config_template }}"
        owner: root
        group: root
        mode: "0644"
      with_items: "{{ web_server }}"
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'

    - name: Start web server service
      service:
        name: "{{ item.service }}"
        state: started
        enabled: yes
      with_items: "{{ web_server }}"
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'

    - name: Allow traffic on port 80 ubuntu
      ufw:
        rule: allow
        port: 80
      when: ansible_distribution == 'Ubuntu'

    - name: Allow traffic on port 80 centos
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
      when: ansible_distribution == 'CentOS'

  handlers:
    - name: Restart web server
      service:
        name: "{{ item.service }}"
        state: restarted
      with_items: "{{ web_server }}"
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
