---
- name: Install and configure nginx, php and database on Centos and Ubuntu
  hosts: webservers
  become: true

  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install PHP on CentOS
      yum:
        name: php
        state: present
      when: ansible_os_family == "RedHat"

    - name: Installation install software-properties-common
      apt: name=software-properties-common
      when: ansible_os_family == "Debian"

    - name: "Repo PHP 7.4"
      apt_repository:
        repo="ppa:ondrej/php"
      when: ansible_os_family == "Debian"

    - name: "Updating the repo"
      apt: update_cache=yes
      when: ansible_os_family == "Debian"

    - name: Installation PHP 7.4
      apt: name=php7.4 state=present
      when: ansible_os_family == "Debian"

    - name: install lamp stack
      apt:
        pkg:
          - php7.4-mysql
          - php7.4-curl
          - php7.4-json
          - php7.4-cgi
          - php7.4-xsl
          - php7.4-cgi
          - php7.4-gd
          - php7.4-mbstring
          - php7.4-zip
          - php7.4-xmlrpc
          - php7.4-soap
          - php7.4-intl
          - libapache2-mod-php
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install MariaDB
      yum:
        name: mariadb-server
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Nginx
      package:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

    - name: Allow incoming connections on port 80 CentOS
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_os_family == 'RedHat'

    - name: Allow incoming connections on port 80 Ubuntu
      ufw:
        rule: allow
        port: 80
      when: ansible_os_family == 'Debian'

    - name: Copy Nginx config file
      template:
        src: /home/ansible/ansible-playground/centos_nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart Nginx
      when: ansible_os_family == 'RedHat'

    - name: Copy Nginx sites-enabled file
      template:
        src: /home/ansible/ansible-playground/default
        dest: /etc/nginx/sites-enabled/default
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart Nginx
      when: ansible_os_family == 'Debian'
    
    - name: Copy Nginx sites-available file
      template:
        src: /home/ansible/ansible-playground/default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart Nginx
      when: ansible_os_family == 'Debian'

    - name: Copy web files to /usr/share/nginx/html
      copy:
        src: /home/ansible/ansible-playground/wave_cafe
        dest: /usr/share/nginx/html
        owner: root
        group: root
        mode: "0755"
      when: ansible_os_family == 'RedHat'

    - name: Copy web files to /var/www/html
      copy:
        src: /home/ansible/ansible-playground/wave_cafe
        dest: /var/www/html
        owner: root
        group: root
        mode: "0755"
      when: ansible_os_family == 'Debian'
    
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted