---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Installation Services
  apt:
    name:
    - mysql-server
    - mysql-client
    - python3-mysqldb
    state: present 

- name: Start ufw
  service: 
    name: ufw 
    state: started 
    enabled: yes

- name: Enable MySQL port in firewall
  ufw:
    rule: allow
    port: 3306

- name: Reload UFW configuration
  ufw:
    state: reloaded

- name: Start MySQL service
  service:
    name: mysql
    state: started

- name: Copy dump file
  template:
    src: app_db_about.sql.j2
    dest: /tmp/dump.sql

- name: Configure Database
  shell: sudo mysql -e "source /tmp/dump.sql"

- name: Copy mysql config
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
    - Restart MySQL