---
# tasks file for python
    - name: Install Python and pip
      package:
        name: python3
        state: present

    - name: Install virtualenv package
      pip:
        name: virtualenv
        state: present

    - name: Create virtual environment
      command: virtualenv /path/to/venv
      args:
        creates: /path/to/venv/bin/activate

    - name: Activate the virtual environment
      command: source /path/to/venv/bin/activate

    - name: Install required Python packages
      pip:
        requirements: /path/to/requirements.txt
        virtualenv: /path/to/venv