---
# tasks file for git
    - name: Install Git package
      package:
        name: git
        state: present
      when: ansible_os_family == 'Debian'

    - name: Clone git repository
      git:
        repo: "{{ programming_planet }}"
        dest: "{{ file_path_ubuntu }}"
        force: yes
      when: ansible_os_family == 'Debian'