---
# tasks file for application
    - name: Change permissions of application directory
      file:
        path: "{{ application_path }}"
        state: directory
        recurse: yes
        mode: "0777"
      when: ansible_os_family == 'Debian'

    - name: Execute install.sh
      command: "{{ application_install_path }}"
      when: ansible_os_family == 'Debian'

    - name: Execute run.sh
      command: "{{ application_run_path }}"
      when: ansible_os_family == 'Debian'