---
# tasks file for application
    - name: Change permissions of application directory
      file:
        path: "{{ application_path }}"
        state: directory
        recurse: yes
        mode: "0777"
      when: ansible_os_family == 'Debian'

    # - name: Create venv
    #   file:
    #     path: "{{ application_venv_path}}"
    #     state: directory
    #     mode: "0777"
    #   when: ansible_os_family == 'Debian'

    # - name: Create virtual environment
    #   command: virtualenv venv
    #   args:
    #     creates: /opt/programming_planet/venv/bin/activate
    #   when: ansible_os_family == 'Debian'

    # - name: Activate the virtual environment
    #   command: source /opt/programming_planet/venv/bin/activate
    #   when: ansible_os_family == 'Debian'

    # - name: Install required Python packages
    #   pip:
    #     requirements: /opt/programming_planet/requirements.txt
    #     virtualenv: "{{ application_venv_path}}"
    #   when: ansible_os_family == 'Debian'

    # - name: Run the Streamlit application
    #   command: streamlit run /opt/programming_planet/app.py
    #   when: ansible_os_family == 'Debian'

    # - name: Execute install.sh
    #   command: "{{ application_install_path }}"
      # when: ansible_os_family == 'Debian'

    - name: prepare environment and install dependencies
      command: sh {{ application_install_path }}
      when: ansible_os_family == 'Debian'

    - name: enable service
      command: sh /opt/programming_planet/install-service.sh