---
- name: Change permissions of application directory
  file:
    path: "{{ application_path }}"
    state: directory
    recurse: yes
    mode: "0777"
  when: ansible_os_family == 'Debian'
- name: prepare environment and install dependencies
  command: sh {{ application_install_path }}
  when: ansible_os_family == 'Debian'
- name: Run Streamlit app in the background
  async: null
  poll: 10
  t: 300
  shell: streamlit run /opt/programming_planet/app.py

    # - name: Run Streamlit app
    #   shell: streamlit run /opt/programming_planet/app.py

    # - name: enable service
    #   command: sh /opt/programming_planet/install-service.sh