---
- name: Change permissions of application directory
  file:
    path: "{{ application_path }}"
    state: directory
    recurse: yes
    mode: "0777"
  when: ansible_os_family == 'Debian'
- name: prepare environment and install dependencies
  shell: sh {{ application_install_path }}
  when: ansible_os_family == 'Debian'
- name: Go to application directory
  shell: cd /opt/programming_planet
# - name: Activate venv
#   shell: source venv/bin/activate
- name: Check current directory
  command: pwd
  register: pwd_output
- name: Verify current directory
  assert:
    that: "'/opt/programming_planet' in pwd_output.stdout"
    success_msg: Current directory is /opt/programming_planet
    fail_msg: Current directory is not /opt/programming_planet
- name: Run application
  shell: streamlit run app.py
  async: 0
  poll: 0
- name: Wait for the application to start
  wait_for:
    host: 0.0.0.0
    port: 8501
    delay: 5
    timeout: 60

    # - name: Run Streamlit app
    #   shell: streamlit run /opt/programming_planet/app.py

    # - name: enable service
    #   command: sh /opt/programming_planet/install-service.sh